### ISSUE TITLE
Support of Academicons 

### ISSUE THREAD

**Issue by Lelio-Brun** [mintyfrankie/brilliant-CV#63] opened 2024-09-24 14:33 UTC
It would be nice to support [Academicons](https://jpswalsh.github.io/academicons/), to allow more icons to be used in an academic context (Google Scholar, DBLP, etc).

It looks like there is already a [recent Typst package](https://typst.app/universe/package/use-academicons) for it that follows the architecture of the Fontawesome package used by brilliant-CV, so I imagine adding support for it would not be too complex.

We could have hard-coded `personal.info` properties like `github`, `linkedin` and such, or simply a `personal.info.custom-*` generic property `academicIcon` akin to `awesomeIcon`.

**Comment by mintyfrankie** [comment] 2024-09-25 07:46
I will take a look at this iconset @Lelio-Brun, thanks for the proposal.

But also in theory, I will be less inclined to propose all new changes to icons as an opinionated design, while there are already functionalities (with `personal.info.custom-*` where you might plugin any images or boxes you like). Did you have any difficulties making the academicons work with the custom fields?

**Comment by Lelio-Brun** [comment] 2024-09-25 18:08
I understand the concern. Academicons has been designed as an extension of Fontawesome, that's why I figured it could be candidate to integration.

On the other hand, I have been unable to make the `image` property work in `personal.info.custom-*`. I identified several problems I faced: 
1. I cannot find an easy way to write Typst code in the metadata using external format (TOML, JSON, etc.)
2. When defining the metadata directly as nested Typst dictionaries, I got a compilation error (both when using `image()` or `box()`: 
   ```
   error: type content has no method `with`
      ┌─ @preview/brilliant-cv:2.0.2/cv.typ:93:21
      │
   93 │           icon = img.with(width: 10pt)
      │                      ^^^^
   ```
   Indeed, from what I can tell, in Typst, something like: 
   ```
   #let b = image(path)
   #b.with(width: 50pt)
   ```
   produces the same kind of error... Now something like this does work:
   ```
   #let b(width: 10pt) = image(path, width: width)
   #b.with(width: 50pt)()
   ```
   I think the problem is that in the package code, `img` is already evaluated content, not a function, while `with()` is a method that should be applied to a function to produce another function. Another solution to avoid the need to handle functions everywhere would be to embed `img` into a box like: `box(img, width: 10pt)`.

**Comment by mintyfrankie** [comment] 2024-09-25 20:10
This is getting interesting here, thanks for the additional input!

Indeed it was tricky to balance between flexibility and modularity; Typst compiler has not yet been too handy in this regard since a good while. I haven't got the time to sit down and take a look on it, but will try to get this done by the end of the weekend.

**Comment by mintyfrankie** [comment] 2024-10-09 12:29
Hi sorry for the late reply, it's been a extremely busy month.

Regarding our latest discussion, some remarks:

1. I confirmed that the `img` functionality is broken, partly because there was a bug (it got evaluated directly instead of being `eval` in the template), but also because it would not be working given Typst's path handling mechanism. This one is not resolvable for the moment. 
2. For the Academicons implementation, it can also be complicated as I just checked the package you mentioned -- it's not simple invocation like awesome-icons package (you input the name of the icon and call it a day). Once again, this is the functionality that toml implementation can not unfortunately handle. 

I think we will have to imagine other ways to extend the flexibility, as people are somewhat really looking forward to customizing the header info icons, yet it's going to be tricky for TOML to do this kind of job.

**Comment by mintyfrankie** [comment] 2024-10-09 12:31
I can confirm that Academicons will not be hardcoded into our template, so in favor of that I am closing this issue, sorry.

Regarding the subject of header info icons flexibility, I will open another issue to centralize the discussion, feel free to leave your thoughts there!

**Closed by mintyfrankie** 2024-10-09 12:31 UTC
Labels: bug, feature request

**Comment by Lelio-Brun** [comment] 2024-10-10 02:15
> 2\. I just checked the package you mentioned -- it's not simple invocation like awesome-icons package (you input the name of the icon and call it a day).

I thought it was though, `#fa-icon("chess-queen")` versus `#ai-icon("lattes")`?
